; 8x8 Standard ASCII Character Set (0-127) for Antic mode 2
;--0--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
;--1--------------
        .BYTE 126 
        .BYTE 129 
        .BYTE 165 
        .BYTE 129 
        .BYTE 189 
        .BYTE 153 
        .BYTE 129 
        .BYTE 126 
;--2--------------
        .BYTE 126 
        .BYTE 255 
        .BYTE 219 
        .BYTE 255 
        .BYTE 195 
        .BYTE 231 
        .BYTE 255 
        .BYTE 126 
;--3--------------
        .BYTE 0 
        .BYTE 54 
        .BYTE 127 
        .BYTE 127 
        .BYTE 62 
        .BYTE 28 
        .BYTE 8 
        .BYTE 0 
;--4--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 60 
        .BYTE 126 
        .BYTE 126 
        .BYTE 60 
        .BYTE 24 
        .BYTE 0 
;--5--------------
        .BYTE 0 
        .BYTE 28 
        .BYTE 28 
        .BYTE 119 
        .BYTE 119 
        .BYTE 8 
        .BYTE 28 
        .BYTE 0 
;--6--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 60 
        .BYTE 126 
        .BYTE 126 
        .BYTE 24 
        .BYTE 60 
        .BYTE 0 
;--7--------------
        .BYTE 120 
        .BYTE 96 
        .BYTE 120 
        .BYTE 96 
        .BYTE 126 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--8--------------
        .BYTE 255 
        .BYTE 255 
        .BYTE 231 
        .BYTE 195 
        .BYTE 195 
        .BYTE 231 
        .BYTE 255 
        .BYTE 255 
;--9--------------
        .BYTE 120 
        .BYTE 96 
        .BYTE 120 
        .BYTE 96 
        .BYTE 126 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--10--------------
        .BYTE 120 
        .BYTE 96 
        .BYTE 120 
        .BYTE 96 
        .BYTE 126 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--11--------------
        .BYTE 120 
        .BYTE 96 
        .BYTE 120 
        .BYTE 96 
        .BYTE 126 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--12--------------
        .BYTE 120 
        .BYTE 96 
        .BYTE 120 
        .BYTE 96 
        .BYTE 126 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--13--------------
        .BYTE 120 
        .BYTE 96 
        .BYTE 120 
        .BYTE 96 
        .BYTE 126 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--14--------------
        .BYTE 127 
        .BYTE 99 
        .BYTE 127 
        .BYTE 99 
        .BYTE 99 
        .BYTE 103 
        .BYTE 230 
        .BYTE 192 
;--15--------------
        .BYTE 153 
        .BYTE 90 
        .BYTE 60 
        .BYTE 231 
        .BYTE 231 
        .BYTE 60 
        .BYTE 90 
        .BYTE 153 
;--16--------------
        .BYTE 16 
        .BYTE 24 
        .BYTE 28 
        .BYTE 30 
        .BYTE 28 
        .BYTE 24 
        .BYTE 16 
        .BYTE 0 
;--17--------------
        .BYTE 8 
        .BYTE 24 
        .BYTE 56 
        .BYTE 120 
        .BYTE 56 
        .BYTE 24 
        .BYTE 8 
        .BYTE 0 
;--18--------------
        .BYTE 24 
        .BYTE 60 
        .BYTE 126 
        .BYTE 24 
        .BYTE 24 
        .BYTE 126 
        .BYTE 60 
        .BYTE 24 
;--19--------------
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 0 
        .BYTE 102 
        .BYTE 0 
;--20--------------
        .BYTE 127 
        .BYTE 219 
        .BYTE 219 
        .BYTE 123 
        .BYTE 27 
        .BYTE 27 
        .BYTE 27 
        .BYTE 0 
;--21--------------
        .BYTE 62 
        .BYTE 99 
        .BYTE 56 
        .BYTE 108 
        .BYTE 108 
        .BYTE 56 
        .BYTE 204 
        .BYTE 120 
;--22--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 255 
        .BYTE 255 
        .BYTE 255 
        .BYTE 255 
;--23--------------
        .BYTE 24 
        .BYTE 60 
        .BYTE 126 
        .BYTE 24 
        .BYTE 126 
        .BYTE 60 
        .BYTE 24 
        .BYTE 255 
;--24--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 60 
        .BYTE 126 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
;--25--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 126 
        .BYTE 60 
        .BYTE 24 
        .BYTE 0 
;--26--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 12 
        .BYTE 126 
        .BYTE 12 
        .BYTE 24 
        .BYTE 0 
        .BYTE 0 
;--27--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 48 
        .BYTE 126 
        .BYTE 48 
        .BYTE 24 
        .BYTE 0 
        .BYTE 0 
;--28--------------
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 31 
        .BYTE 31 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
;--29--------------
        .BYTE 120 
        .BYTE 96 
        .BYTE 120 
        .BYTE 96 
        .BYTE 126 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--30--------------
        .BYTE 120 
        .BYTE 96 
        .BYTE 120 
        .BYTE 96 
        .BYTE 126 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--31--------------
        .BYTE 120 
        .BYTE 96 
        .BYTE 120 
        .BYTE 96 
        .BYTE 126 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--32--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
;--33--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
        .BYTE 24 
        .BYTE 0 
;--34--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
;--35--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 255 
        .BYTE 102 
        .BYTE 102 
        .BYTE 255 
        .BYTE 102 
        .BYTE 0 
;--36--------------
        .BYTE 24 
        .BYTE 62 
        .BYTE 96 
        .BYTE 60 
        .BYTE 6 
        .BYTE 124 
        .BYTE 24 
        .BYTE 0 
;--37--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 108 
        .BYTE 24 
        .BYTE 48 
        .BYTE 102 
        .BYTE 70 
        .BYTE 0 
;--38--------------
        .BYTE 28 
        .BYTE 54 
        .BYTE 28 
        .BYTE 56 
        .BYTE 111 
        .BYTE 102 
        .BYTE 59 
        .BYTE 0 
;--39--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
;--40--------------
        .BYTE 0 
        .BYTE 14 
        .BYTE 28 
        .BYTE 24 
        .BYTE 24 
        .BYTE 28 
        .BYTE 14 
        .BYTE 0 
;--41--------------
        .BYTE 0 
        .BYTE 112 
        .BYTE 56 
        .BYTE 24 
        .BYTE 24 
        .BYTE 56 
        .BYTE 112 
        .BYTE 0 
;--42--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 60 
        .BYTE 255 
        .BYTE 60 
        .BYTE 102 
        .BYTE 0 
        .BYTE 0 
;--43--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 126 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
        .BYTE 0 
;--44--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 48 
;--45--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 126 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
;--46--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
;--47--------------
        .BYTE 0 
        .BYTE 6 
        .BYTE 12 
        .BYTE 24 
        .BYTE 48 
        .BYTE 96 
        .BYTE 64 
        .BYTE 0 
;--48--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 110 
        .BYTE 118 
        .BYTE 102 
        .BYTE 60 
        .BYTE 0 
;--49--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 56 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 126 
        .BYTE 0 
;--50--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 12 
        .BYTE 24 
        .BYTE 48 
        .BYTE 126 
        .BYTE 0 
;--51--------------
        .BYTE 0 
        .BYTE 126 
        .BYTE 12 
        .BYTE 24 
        .BYTE 12 
        .BYTE 102 
        .BYTE 60 
        .BYTE 0 
;--52--------------
        .BYTE 0 
        .BYTE 12 
        .BYTE 28 
        .BYTE 60 
        .BYTE 108 
        .BYTE 126 
        .BYTE 12 
        .BYTE 0 
;--53--------------
        .BYTE 0 
        .BYTE 126 
        .BYTE 96 
        .BYTE 124 
        .BYTE 6 
        .BYTE 102 
        .BYTE 60 
        .BYTE 0 
;--54--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 96 
        .BYTE 124 
        .BYTE 102 
        .BYTE 102 
        .BYTE 60 
        .BYTE 0 
;--55--------------
        .BYTE 0 
        .BYTE 126 
        .BYTE 6 
        .BYTE 12 
        .BYTE 24 
        .BYTE 48 
        .BYTE 48 
        .BYTE 0 
;--56--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 60 
        .BYTE 102 
        .BYTE 102 
        .BYTE 60 
        .BYTE 0 
;--57--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 62 
        .BYTE 6 
        .BYTE 12 
        .BYTE 56 
        .BYTE 0 
;--58--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
;--59--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
        .BYTE 24 
        .BYTE 24 
        .BYTE 48 
;--60--------------
        .BYTE 6 
        .BYTE 12 
        .BYTE 24 
        .BYTE 48 
        .BYTE 24 
        .BYTE 12 
        .BYTE 6 
        .BYTE 0 
;--61--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 126 
        .BYTE 0 
        .BYTE 0 
        .BYTE 126 
        .BYTE 0 
        .BYTE 0 
;--62--------------
        .BYTE 96 
        .BYTE 48 
        .BYTE 24 
        .BYTE 12 
        .BYTE 24 
        .BYTE 48 
        .BYTE 96 
        .BYTE 0 
;--63--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 12 
        .BYTE 24 
        .BYTE 0 
        .BYTE 24 
        .BYTE 0 
;--64--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 110 
        .BYTE 110 
        .BYTE 96 
        .BYTE 62 
        .BYTE 0 
;--65--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 60 
        .BYTE 102 
        .BYTE 102 
        .BYTE 126 
        .BYTE 102 
        .BYTE 0 
;--66--------------
        .BYTE 0 
        .BYTE 124 
        .BYTE 102 
        .BYTE 124 
        .BYTE 102 
        .BYTE 102 
        .BYTE 124 
        .BYTE 0 
;--67--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 96 
        .BYTE 96 
        .BYTE 102 
        .BYTE 60 
        .BYTE 0 
;--68--------------
        .BYTE 0 
        .BYTE 120 
        .BYTE 108 
        .BYTE 102 
        .BYTE 102 
        .BYTE 108 
        .BYTE 120 
        .BYTE 0 
;--69--------------
        .BYTE 0 
        .BYTE 126 
        .BYTE 96 
        .BYTE 124 
        .BYTE 96 
        .BYTE 96 
        .BYTE 126 
        .BYTE 0 
;--70--------------
        .BYTE 0 
        .BYTE 126 
        .BYTE 96 
        .BYTE 124 
        .BYTE 96 
        .BYTE 96 
        .BYTE 96 
        .BYTE 0 
;--71--------------
        .BYTE 0 
        .BYTE 62 
        .BYTE 96 
        .BYTE 96 
        .BYTE 110 
        .BYTE 102 
        .BYTE 62 
        .BYTE 0 
;--72--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 102 
        .BYTE 126 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 0 
;--73--------------
        .BYTE 0 
        .BYTE 126 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 126 
        .BYTE 0 
;--74--------------
        .BYTE 0 
        .BYTE 6 
        .BYTE 6 
        .BYTE 6 
        .BYTE 6 
        .BYTE 102 
        .BYTE 60 
        .BYTE 0 
;--75--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 108 
        .BYTE 120 
        .BYTE 120 
        .BYTE 108 
        .BYTE 102 
        .BYTE 0 
;--76--------------
        .BYTE 0 
        .BYTE 96 
        .BYTE 96 
        .BYTE 96 
        .BYTE 96 
        .BYTE 96 
        .BYTE 126 
        .BYTE 0 
;--77--------------
        .BYTE 0 
        .BYTE 99 
        .BYTE 119 
        .BYTE 127 
        .BYTE 107 
        .BYTE 99 
        .BYTE 99 
        .BYTE 0 
;--78--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 118 
        .BYTE 126 
        .BYTE 126 
        .BYTE 110 
        .BYTE 102 
        .BYTE 0 
;--79--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 60 
        .BYTE 0 
;--80--------------
        .BYTE 0 
        .BYTE 124 
        .BYTE 102 
        .BYTE 102 
        .BYTE 124 
        .BYTE 96 
        .BYTE 96 
        .BYTE 0 
;--81--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 108 
        .BYTE 54 
        .BYTE 0 
;--82--------------
        .BYTE 0 
        .BYTE 124 
        .BYTE 102 
        .BYTE 102 
        .BYTE 124 
        .BYTE 108 
        .BYTE 102 
        .BYTE 0 
;--83--------------
        .BYTE 0 
        .BYTE 60 
        .BYTE 96 
        .BYTE 60 
        .BYTE 6 
        .BYTE 6 
        .BYTE 60 
        .BYTE 0 
;--84--------------
        .BYTE 0 
        .BYTE 126 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
;--85--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 126 
        .BYTE 0 
;--86--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 60 
        .BYTE 24 
        .BYTE 0 
;--87--------------
        .BYTE 0 
        .BYTE 99 
        .BYTE 99 
        .BYTE 107 
        .BYTE 127 
        .BYTE 119 
        .BYTE 99 
        .BYTE 0 
;--88--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 102 
        .BYTE 60 
        .BYTE 60 
        .BYTE 102 
        .BYTE 102 
        .BYTE 0 
;--89--------------
        .BYTE 0 
        .BYTE 102 
        .BYTE 102 
        .BYTE 60 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
;--90--------------
        .BYTE 0 
        .BYTE 126 
        .BYTE 12 
        .BYTE 24 
        .BYTE 48 
        .BYTE 96 
        .BYTE 126 
        .BYTE 0 
;--91--------------
        .BYTE 0 
        .BYTE 30 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 30 
        .BYTE 0 
;--92--------------
        .BYTE 0 
        .BYTE 64 
        .BYTE 96 
        .BYTE 48 
        .BYTE 24 
        .BYTE 12 
        .BYTE 6 
        .BYTE 0 
;--93--------------
        .BYTE 0 
        .BYTE 120 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 120 
        .BYTE 0 
;--94--------------
        .BYTE 0 
        .BYTE 8 
        .BYTE 28 
        .BYTE 54 
        .BYTE 99 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
;--95--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 255 
        .BYTE 0 
;--96--------------
        .BYTE 48 
        .BYTE 48 
        .BYTE 24 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
;--97--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 60 
        .BYTE 6 
        .BYTE 62 
        .BYTE 102 
        .BYTE 62 
        .BYTE 0 
;--98--------------
        .BYTE 0 
        .BYTE 96 
        .BYTE 96 
        .BYTE 124 
        .BYTE 102 
        .BYTE 102 
        .BYTE 124 
        .BYTE 0 
;--99--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 60 
        .BYTE 96 
        .BYTE 96 
        .BYTE 96 
        .BYTE 60 
        .BYTE 0 
;--100--------------
        .BYTE 0 
        .BYTE 6 
        .BYTE 6 
        .BYTE 62 
        .BYTE 102 
        .BYTE 102 
        .BYTE 62 
        .BYTE 0 
;--101--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 126 
        .BYTE 96 
        .BYTE 60 
        .BYTE 0 
;--102--------------
        .BYTE 0 
        .BYTE 14 
        .BYTE 24 
        .BYTE 62 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 0 
;--103--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 62 
        .BYTE 102 
        .BYTE 102 
        .BYTE 62 
        .BYTE 6 
        .BYTE 124 
;--104--------------
        .BYTE 0 
        .BYTE 96 
        .BYTE 96 
        .BYTE 124 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 0 
;--105--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 0 
        .BYTE 56 
        .BYTE 24 
        .BYTE 24 
        .BYTE 60 
        .BYTE 0 
;--106--------------
        .BYTE 0 
        .BYTE 6 
        .BYTE 0 
        .BYTE 6 
        .BYTE 6 
        .BYTE 6 
        .BYTE 6 
        .BYTE 60 
;--107--------------
        .BYTE 0 
        .BYTE 96 
        .BYTE 96 
        .BYTE 108 
        .BYTE 120 
        .BYTE 108 
        .BYTE 102 
        .BYTE 0 
;--108--------------
        .BYTE 0 
        .BYTE 56 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 60 
        .BYTE 0 
;--109--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 102 
        .BYTE 127 
        .BYTE 127 
        .BYTE 107 
        .BYTE 99 
        .BYTE 0 
;--110--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 124 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 0 
;--111--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 60 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 60 
        .BYTE 0 
;--112--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 124 
        .BYTE 102 
        .BYTE 102 
        .BYTE 124 
        .BYTE 96 
        .BYTE 96 
;--113--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 62 
        .BYTE 102 
        .BYTE 102 
        .BYTE 62 
        .BYTE 6 
        .BYTE 6 
;--114--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 124 
        .BYTE 102 
        .BYTE 96 
        .BYTE 96 
        .BYTE 96 
        .BYTE 0 
;--115--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 62 
        .BYTE 96 
        .BYTE 60 
        .BYTE 6 
        .BYTE 124 
        .BYTE 0 
;--116--------------
        .BYTE 0 
        .BYTE 24 
        .BYTE 126 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 14 
        .BYTE 0 
;--117--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 62 
        .BYTE 0 
;--118--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 60 
        .BYTE 24 
        .BYTE 0 
;--119--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 99 
        .BYTE 107 
        .BYTE 127 
        .BYTE 62 
        .BYTE 54 
        .BYTE 0 
;--120--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 102 
        .BYTE 60 
        .BYTE 24 
        .BYTE 60 
        .BYTE 102 
        .BYTE 0 
;--121--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 102 
        .BYTE 102 
        .BYTE 102 
        .BYTE 62 
        .BYTE 12 
        .BYTE 120 
;--122--------------
        .BYTE 0 
        .BYTE 0 
        .BYTE 126 
        .BYTE 12 
        .BYTE 24 
        .BYTE 48 
        .BYTE 126 
        .BYTE 0 
;--123--------------
        .BYTE 28 
        .BYTE 48 
        .BYTE 48 
        .BYTE 224 
        .BYTE 48 
        .BYTE 48 
        .BYTE 28 
        .BYTE 0 
;--124--------------
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
        .BYTE 24 
;--125--------------
        .BYTE 224 
        .BYTE 48 
        .BYTE 48 
        .BYTE 28 
        .BYTE 48 
        .BYTE 48 
        .BYTE 224 
        .BYTE 0 
;--126--------------
        .BYTE 118 
        .BYTE 220 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
        .BYTE 0 
;--127--------------
        .BYTE 0 
        .BYTE 16 
        .BYTE 56 
        .BYTE 108 
        .BYTE 198 
        .BYTE 198 
        .BYTE 254 
        .BYTE 0 
